# Generated by Django 4.0.4 on 2022-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cards_alter_vacancies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('task', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.RenameModel(
            old_name='vacancies',
            new_name='VacanciesCategory',
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
